config/routes.rb
Rails.application.routes.draw do
  resources :works

  root 'welcome#index'
  get '/', :to => 'welcome#index', :as => :home
  get '/about',:to =>'welcome#about', :as => :about
  get '/contact',:to =>'welcome#contact', :as => :contact
  get '/portfolio', :to =>'works#index', :as => :portfolio

end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @carousel_photos = ['sloth-money-mind.png', 'sloth-cash-money.jpg','sloth-stripper.jpg','sloth-cigar-spacesuit.jpg','sloth_astronaut.jpg','sloth-floating-space.jpg']
    @carousel_content_counter = 0
    @carousel_photo_counter = 0
    @robby = params[:robby]
  end

  def about
    @robby = params[:robby]
  end

  def contact
    @robby = params[:robby]
  end
  private
  def robby
    @robby = params[:robby]
    if @robby
      session[:robby] = @robby
    end
    if @robby
    else
      @robby=session[:robby]
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <!-- Latest compiled and minified CSS -->
      <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
      <!-- Latest compiled and minified JavaScript -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag 'custom.css'%>
    </head>

<body role="document" class="container">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Agile Philosopher</a>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav ">
            <li><a class = "active" href="<%=home_path%>">Home</a></li>
            <li><a class = "active" href="<%=about_path%>">About</a></li>
            <li><a class= "active" href="<%=portfolio_path%>">Portfolio</a></li>
            <li><a class = "active" href="<%=contact_path%>">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="jumbotron col-6-md">

            <h1 id="inline-block" class="span8">
              The Agile Philosopher
            </h1>
            <%=image_tag 'profile.jpg', class:'image-shadow image-round image-shrink img-responsive profile_picture pull-right span4 offset8'%>
            <p style="margin-left:4%" id="inline-block" class="span8">
              Let's inject some existentialism into that daily software grind.
            </p>
      </div>
    </div>
      <%= yield %>

    </div>
    <% if @robby == 'yep' %>
    <div>
      <%=image_tag('brace-yourself.jpg', class: "img-rounded img-responsive center-block")%>
    </div>
<%end%>
<p></p>
<div class="page-header" </div>
<p></p>
<div class="btn-group btn-group-justified">
  <a href="<%=@PathParam%>?robby=yep" class="btn btn-primary">Are you Robby?</a>
  <a href="<%=@PathParam%>?robby=nope" class="btn btn-danger">Not Robby?</a>
</div>
</body>
</html>

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agile Philosopher About</title>
</head>
    <body>
        <div class="page-header">
            <h1>About meh</h1>
        </div>
        <div>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum nunc felis, non rutrum eros lacinia vitae. Proin ultrices, ex vel sollicitudin cursus, turpis tellus vehicula ex, condimentum fringilla lacus odio et mi. Praesent auctor tempus posuere. Suspendisse feugiat non quam at egestas. Nullam risus turpis, aliquet id magna eget, porta accumsan augue. Nullam interdum id mi vel rutrum. Vestibulum auctor neque id dui ornare, vitae consectetur turpis sodales. Donec ornare, dui at molestie placerat, tortor quam viverra metus, et gravida mauris tortor sit amet nisi. Vivamus dui mi, placerat quis mi vestibulum, posuere viverra ipsum. Nunc vel est vel diam convallis dignissim a vitae velit. Morbi porta risus at gravida vehicula.
          </p>
          <p>
            Nam pharetra rhoncus lorem vitae molestie. Nullam interdum dui eu est molestie, et aliquam magna maximus. Curabitur at gravida metus. Quisque non dapibus mauris. Nunc non aliquam purus, sed laoreet odio. Mauris lorem nisl, laoreet id neque nec, vulputate mattis tellus. Curabitur eget velit turpis. Aliquam suscipit dignissim dolor nec consectetur. In sagittis, urna ut suscipit porta, orci orci molestie mauris, ut ullamcorper libero risus ac tortor. Sed posuere, leo vel gravida mattis, diam diam dictum velit, sit amet vehicula neque erat consectetur mauris. Integer non neque a turpis tristique efficitur porta eget risus. Quisque ornare diam eget turpis elementum viverra pharetra nec turpis.
          </p>
          <p>
            Praesent sollicitudin a massa sit amet egestas. Mauris eleifend consectetur tincidunt. Nullam eu elit nisl. Vivamus et mollis enim. Donec urna neque, commodo vel eros sed, tincidunt semper neque. Maecenas non turpis arcu. Duis egestas lacus enim, vulputate convallis elit ultrices nec. Aliquam at pellentesque nulla. Phasellus molestie est augue, sit amet vulputate nibh blandit ac.
          </p>
          <p>
            Nam nisl sem, laoreet et risus in, dignissim imperdiet metus. Sed sollicitudin diam quis nisl hendrerit pellentesque. Proin dapibus, felis eu volutpat venenatis, sem urna interdum est, sit amet volutpat purus libero nec elit. Mauris eu tristique tellus, id ornare risus. Curabitur suscipit sem vel dolor venenatis tincidunt. Ut tempor ligula eu lacinia consectetur. Ut vehicula, urna sit amet accumsan faucibus, lectus elit varius velit, non venenatis urna ipsum ac nisi. Aliquam convallis varius accumsan. Ut quis ex congue eros tempus vestibulum nec vitae urna. Morbi sed tempor sapien. Aenean imperdiet mauris sit amet nunc viverra laoreet hendrerit vel leo. Integer lobortis ac dui a interdum.
          </p>
          <p>
            Sed non pulvinar felis. Aenean scelerisque enim purus, eu hendrerit nulla lacinia ac. Nam eu velit tincidunt risus elementum eleifend sed quis leo. Phasellus at erat nec erat sodales luctus. Nam nisi sem, ornare in massa ut, volutpat semper dolor. Aenean in rutrum sapien. Vestibulum sed magna risus. Suspendisse tempor, elit sit amet hendrerit ornare, velit metus feugiat arcu, quis efficitur ex ipsum vitae mauris. Praesent varius felis nunc, vitae scelerisque mi fermentum quis. Nunc vehicula erat arcu, a pharetra libero molestie eget.
          </p>
          <p>
            In dictum metus vitae turpis ullamcorper, eu commodo nibh tincidunt. Fusce at ligula dignissim, lacinia orci quis, maximus justo. Ut justo odio, blandit tincidunt odio nec, molestie porta sem. Ut ac leo in mauris cursus aliquam nec non leo. Donec dui purus, ultricies nec posuere sed, posuere vel nisl. Nullam ac cursus quam. Aliquam tristique nec sem a vehicula. Etiam vel diam iaculis ligula ornare tincidunt. Morbi et erat aliquam nisl ultricies dignissim condimentum sit amet quam. Aenean pellentesque, sapien vel aliquam aliquet, quam justo volutpat velit, nec porttitor mi orci ut arcu. Sed porta finibus magna a tristique. Morbi finibus dui nec felis blandit, eu laoreet sem consectetur. In pretium dui sed purus feugiat, et consequat neque bibendum. Fusce sit amet mauris in risus posuere ullamcorper. Ut posuere tellus at est finibus, eu tincidunt augue fermentum. Aliquam eleifend, nibh at condimentum iaculis, nulla magna vehicula lectus, non vulputate nibh ex a lectus.
          </p>
        </div>
    </body>
</html>

app/views/welcome/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agile Philosopher Contact</title>

</head>
    <body>
        <div class="page-header">
            <h1>Contact this!</h1>
        </div>
        <div>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum nunc felis, non rutrum eros lacinia vitae. Proin ultrices, ex vel sollicitudin cursus, turpis tellus vehicula ex, condimentum fringilla lacus odio et mi. Praesent auctor tempus posuere. Suspendisse feugiat non quam at egestas. Nullam risus turpis, aliquet id magna eget, porta accumsan augue. Nullam interdum id mi vel rutrum. Vestibulum auctor neque id dui ornare, vitae consectetur turpis sodales. Donec ornare, dui at molestie placerat, tortor quam viverra metus, et gravida mauris tortor sit amet nisi. Vivamus dui mi, placerat quis mi vestibulum, posuere viverra ipsum. Nunc vel est vel diam convallis dignissim a vitae velit. Morbi porta risus at gravida vehicula.
          </p>
          <p>
            Nam pharetra rhoncus lorem vitae molestie. Nullam interdum dui eu est molestie, et aliquam magna maximus. Curabitur at gravida metus. Quisque non dapibus mauris. Nunc non aliquam purus, sed laoreet odio. Mauris lorem nisl, laoreet id neque nec, vulputate mattis tellus. Curabitur eget velit turpis. Aliquam suscipit dignissim dolor nec consectetur. In sagittis, urna ut suscipit porta, orci orci molestie mauris, ut ullamcorper libero risus ac tortor. Sed posuere, leo vel gravida mattis, diam diam dictum velit, sit amet vehicula neque erat consectetur mauris. Integer non neque a turpis tristique efficitur porta eget risus. Quisque ornare diam eget turpis elementum viverra pharetra nec turpis.
          </p>
          <p>
            Praesent sollicitudin a massa sit amet egestas. Mauris eleifend consectetur tincidunt. Nullam eu elit nisl. Vivamus et mollis enim. Donec urna neque, commodo vel eros sed, tincidunt semper neque. Maecenas non turpis arcu. Duis egestas lacus enim, vulputate convallis elit ultrices nec. Aliquam at pellentesque nulla. Phasellus molestie est augue, sit amet vulputate nibh blandit ac.
          </p>
          <p>
            Nam nisl sem, laoreet et risus in, dignissim imperdiet metus. Sed sollicitudin diam quis nisl hendrerit pellentesque. Proin dapibus, felis eu volutpat venenatis, sem urna interdum est, sit amet volutpat purus libero nec elit. Mauris eu tristique tellus, id ornare risus. Curabitur suscipit sem vel dolor venenatis tincidunt. Ut tempor ligula eu lacinia consectetur. Ut vehicula, urna sit amet accumsan faucibus, lectus elit varius velit, non venenatis urna ipsum ac nisi. Aliquam convallis varius accumsan. Ut quis ex congue eros tempus vestibulum nec vitae urna. Morbi sed tempor sapien. Aenean imperdiet mauris sit amet nunc viverra laoreet hendrerit vel leo. Integer lobortis ac dui a interdum.
          </p>
          <p>
            Sed non pulvinar felis. Aenean scelerisque enim purus, eu hendrerit nulla lacinia ac. Nam eu velit tincidunt risus elementum eleifend sed quis leo. Phasellus at erat nec erat sodales luctus. Nam nisi sem, ornare in massa ut, volutpat semper dolor. Aenean in rutrum sapien. Vestibulum sed magna risus. Suspendisse tempor, elit sit amet hendrerit ornare, velit metus feugiat arcu, quis efficitur ex ipsum vitae mauris. Praesent varius felis nunc, vitae scelerisque mi fermentum quis. Nunc vehicula erat arcu, a pharetra libero molestie eget.
          </p>
          <p>
            In dictum metus vitae turpis ullamcorper, eu commodo nibh tincidunt. Fusce at ligula dignissim, lacinia orci quis, maximus justo. Ut justo odio, blandit tincidunt odio nec, molestie porta sem. Ut ac leo in mauris cursus aliquam nec non leo. Donec dui purus, ultricies nec posuere sed, posuere vel nisl. Nullam ac cursus quam. Aliquam tristique nec sem a vehicula. Etiam vel diam iaculis ligula ornare tincidunt. Morbi et erat aliquam nisl ultricies dignissim condimentum sit amet quam. Aenean pellentesque, sapien vel aliquam aliquet, quam justo volutpat velit, nec porttitor mi orci ut arcu. Sed porta finibus magna a tristique. Morbi finibus dui nec felis blandit, eu laoreet sem consectetur. In pretium dui sed purus feugiat, et consequat neque bibendum. Fusce sit amet mauris in risus posuere ullamcorper. Ut posuere tellus at est finibus, eu tincidunt augue fermentum. Aliquam eleifend, nibh at condimentum iaculis, nulla magna vehicula lectus, non vulputate nibh ex a lectus.
          </p>
        </div>
    </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agile Philosopher Home</title>
</head>
    <body>
        <div class="page-header">
            <h1>sloths-R-us</h1>
        </div>

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <% @carousel_photos.each do%>
                    <% if @carousel_photo_counter == 0%>
                        <li data-target="#myCarousel" data-slide-to="@carousel_photo_counter" class="active"></li>
                    <% else %>
                        <li data-target="#myCarousel" data-slide-to="@carousel_photo_counter"></li>
                    <%end%>
                <%end%>
              </ol>

              <div class="carousel-inner" role="listbox">
                  <%@carousel_photos.each do |my_photo| %>
                    <% if @carousel_content_counter == 0 %>
                      <div class="item active">
                        <%= image_tag(my_photo, class:"img-responsive carousel_photo img-rounded")%>
                      </div>
                    <% else %>
                        <div class="item">
                          <%= image_tag(my_photo, class:"img-responsive carousel_photo img-rounded")%>
                        </div>
                    <%end%>
                    <% @carousel_content_counter = @carousel_content_counter+=1%>
                  <%end%>
              </div>
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="page-header">
          <h1>Home</h1>
        </div>
        <div class="container-fluid">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum nunc felis, non rutrum eros lacinia vitae. Proin ultrices, ex vel sollicitudin cursus, turpis tellus vehicula ex, condimentum fringilla lacus odio et mi. Praesent auctor tempus posuere. Suspendisse feugiat non quam at egestas. Nullam risus turpis, aliquet id magna eget, porta accumsan augue. Nullam interdum id mi vel rutrum. Vestibulum auctor neque id dui ornare, vitae consectetur turpis sodales. Donec ornare, dui at molestie placerat, tortor quam viverra metus, et gravida mauris tortor sit amet nisi. Vivamus dui mi, placerat quis mi vestibulum, posuere viverra ipsum. Nunc vel est vel diam convallis dignissim a vitae velit. Morbi porta risus at gravida vehicula.
          </p>
          <p>
            Nam pharetra rhoncus lorem vitae molestie. Nullam interdum dui eu est molestie, et aliquam magna maximus. Curabitur at gravida metus. Quisque non dapibus mauris. Nunc non aliquam purus, sed laoreet odio. Mauris lorem nisl, laoreet id neque nec, vulputate mattis tellus. Curabitur eget velit turpis. Aliquam suscipit dignissim dolor nec consectetur. In sagittis, urna ut suscipit porta, orci orci molestie mauris, ut ullamcorper libero risus ac tortor. Sed posuere, leo vel gravida mattis, diam diam dictum velit, sit amet vehicula neque erat consectetur mauris. Integer non neque a turpis tristique efficitur porta eget risus. Quisque ornare diam eget turpis elementum viverra pharetra nec turpis.
          </p>
          <p>
            Praesent sollicitudin a massa sit amet egestas. Mauris eleifend consectetur tincidunt. Nullam eu elit nisl. Vivamus et mollis enim. Donec urna neque, commodo vel eros sed, tincidunt semper neque. Maecenas non turpis arcu. Duis egestas lacus enim, vulputate convallis elit ultrices nec. Aliquam at pellentesque nulla. Phasellus molestie est augue, sit amet vulputate nibh blandit ac.
          </p>
          <p>
            Nam nisl sem, laoreet et risus in, dignissim imperdiet metus. Sed sollicitudin diam quis nisl hendrerit pellentesque. Proin dapibus, felis eu volutpat venenatis, sem urna interdum est, sit amet volutpat purus libero nec elit. Mauris eu tristique tellus, id ornare risus. Curabitur suscipit sem vel dolor venenatis tincidunt. Ut tempor ligula eu lacinia consectetur. Ut vehicula, urna sit amet accumsan faucibus, lectus elit varius velit, non venenatis urna ipsum ac nisi. Aliquam convallis varius accumsan. Ut quis ex congue eros tempus vestibulum nec vitae urna. Morbi sed tempor sapien. Aenean imperdiet mauris sit amet nunc viverra laoreet hendrerit vel leo. Integer lobortis ac dui a interdum.
          </p>
          <p>
            Sed non pulvinar felis. Aenean scelerisque enim purus, eu hendrerit nulla lacinia ac. Nam eu velit tincidunt risus elementum eleifend sed quis leo. Phasellus at erat nec erat sodales luctus. Nam nisi sem, ornare in massa ut, volutpat semper dolor. Aenean in rutrum sapien. Vestibulum sed magna risus. Suspendisse tempor, elit sit amet hendrerit ornare, velit metus feugiat arcu, quis efficitur ex ipsum vitae mauris. Praesent varius felis nunc, vitae scelerisque mi fermentum quis. Nunc vehicula erat arcu, a pharetra libero molestie eget.
          </p>
          <p>
            In dictum metus vitae turpis ullamcorper, eu commodo nibh tincidunt. Fusce at ligula dignissim, lacinia orci quis, maximus justo. Ut justo odio, blandit tincidunt odio nec, molestie porta sem. Ut ac leo in mauris cursus aliquam nec non leo. Donec dui purus, ultricies nec posuere sed, posuere vel nisl. Nullam ac cursus quam. Aliquam tristique nec sem a vehicula. Etiam vel diam iaculis ligula ornare tincidunt. Morbi et erat aliquam nisl ultricies dignissim condimentum sit amet quam. Aenean pellentesque, sapien vel aliquam aliquet, quam justo volutpat velit, nec porttitor mi orci ut arcu. Sed porta finibus magna a tristique. Morbi finibus dui nec felis blandit, eu laoreet sem consectetur. In pretium dui sed purus feugiat, et consequat neque bibendum. Fusce sit amet mauris in risus posuere ullamcorper. Ut posuere tellus at est finibus, eu tincidunt augue fermentum. Aliquam eleifend, nibh at condimentum iaculis, nulla magna vehicula lectus, non vulputate nibh ex a lectus.
          </p>
        </div>


    </body>
</html>

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group-lg">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="field form-group-lg">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control", rows: "10" %>
  </div>
  <div class="actions form-group-lg">
    <%= f.submit class:"btn btn-default", role:"button" %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form' %>
<div class="btn-group">
    <%= link_to 'Show', @work, class: "btn btn-default", role:"button" %>
    <%= link_to 'Back', works_path, class: "btn btn-default", role:"button"%>
</div>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Portfolio Item', new_work_path, class:"btn btn-default pull-right", role:"button" %>
<div class="page-header">
<h1>Portfolio</h1>
</div>

<div>
    <% @works.each do |work| %>
      <div class="btn-group">
        <td><%= link_to 'View', work, class:"btn btn-default", role:"button"%></td>
        <td><%= link_to 'Edit', edit_work_path(work), class:"btn btn-default", role:"button"%></td>
        <td><%= link_to 'Delete', work, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default", role:"button"%></td>
      </div>
      <div class="col-md4">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2 class="text-center"><%= work.name %></h2>
            <div class="page-header"></div>
              <p class="text-justify"><%= work.description %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>
<br>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h2><%=@work.name%></h2>
      <p>
        <strong>Description:</strong>
        <%= @work.description %>
      </p>
      <div class="btn-group">
        <%= link_to 'Edit', edit_work_path(@work), class: "btn btn-default", role: "button" %>
        <%= link_to 'Back', works_path, class: "btn btn-default", role: "button" %>
      </div>
    </div>
  </div>